services:
  - type: web
    name: platano-dulce
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend && npm install --prefix backend
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
